[package]
name = "rew-jsx"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
description = "REW JSX compiler"

[lib]
name = "rew_jsx"
path = "src/lib.rs"

[dependencies]
