[package]
name = "rew-brew"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
description = "BREW compiler and decompiler"

[dependencies]
anyhow = "1.0"
base64 = "0.21.0"
